### ISSUE TITLE
For some reason, the timer does not start counting.

### ISSUE THREAD

**Issue by ZiraiMode** [iamporus/BndrsntchTimer#1]
For some reason, the timer does not start counting.

My config: 
Xiaomi Redmi Note 4x,
Library - 1.0.3

`

    private BndrsntchTimer timer;

        timer = (BndrsntchTimer) findViewById( R.id.timer);

        timer.start( 15000, new BndrsntchTimer.OnTimerElapsedListener()
        {
            @Override
            public void onTimeElapsed( long elapsedDuration, long totalDuration )
            {
                if( elapsedDuration >= totalDuration )
                {
                    Toast.makeText(GuessView.this, "(", Toast.LENGTH_SHORT).show();
                }
            }
        });

`

**Comment by MartB** [comment]
mbTimerElapsed is always false in my case, will dig into this later

**Comment by MartB** [comment]
If you want this to work you need the following line in your fragment / activity.

```
getLifecycle().addObserver( timer.getLifecycleObserver() );
```
