### ISSUE TITLE
resetting BndrsntchTimer doesn't reset animation

### ISSUE THREAD

**Issue by soham24** [iamporus/BndrsntchTimer#4]
`    public void showQ() {
     
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                ObjectAnimator objectAnimator = ObjectAnimator.ofFloat(mRelativeLayout,
                        "alpha", 0f, 1f);
                objectAnimator.setDuration(1500);
                objectAnimator.addListener(new AnimatorListenerAdapter() {
                    @Override
                    public void onAnimationEnd(Animator animation) {
                        mBndrsntchTimer.reset();
                        mBndrsntchTimer.start(6000);
                    }
                });
                objectAnimator.start();
            }
        }, 1000);

    }`

I am showing new questions at a particular time. the timer works as expected. but the timer animations do not work after the first time.
i.e. I did not see any animation when I load the second question or call above method second time

**Comment by iamporus** [comment]
Added OnTimerResetListener to listen for reset event. Issue the next start command when reset is completed.

Closing issue as a fix has been added in [5d34380](https://github.com/iamporus/BndrsntchTimer/commit/5d34380a857285c943432109f829e0b9a37101c4)
Check out the new release from [here](https://jitpack.io/#iamporus/BndrsntchTimer/v2.0.202706).
